server:
  port: 9001
spring:
  datasource:
    name: test
    url: jdbc:mysql://10.27.20.13:3306/mybatis?characterEncoding=utf8&useSSL=false
    username: envision
    password: Envisi0n4321!
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.mybatisdemo.domain.Do
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count = countSql

logging:
  level:
    com.example.mybatisdemo.mapper: debug
